<!--
  1. Replace {Prism Central IP} with yours
  2. Replace {API Key} with yours
  3. Replace {Name} with VDI naming sequence
-->

curl -X 'POST' \
'https://{Prism Central IP}:9440/api/nutanix/v3/vms/list' \
-H 'accept: application/json' \
-H 'Authorization: Basic {API Key}' \
-H 'Content-Type: application/json' \
-d '{
    "kind" : "vm",
    "sort_attribute" : "vm_name",
    "filter" : "vm_name==.*{Name}.*",
    "length" : 1,
    "sort_order" : "DESCENDING",
    "offset" : 0
}'
